export const MANTRAS = [
  'let code die',
  'energy YES. quality NO.',
  'everyone sees the same mantra',
  'mantras repeat',
  'we love repetition',
  'this is a public flok room',
  'there is only one room',
  'press ctrl + enter to run code',
  'BAD CODE ONLY',
  'recording and sharing is encouraged',
  'normalise sharing scrappy fiddles',
  'be brave',
  'embrace death',
  'just let go of what you know',
  'move',
  'make space',
  'you must delete',
  'embrace spaghetti code',
  'add a mantra',
  'all day every day',
];
